MyApp/tests.py:21:1: W391 blank line at end of file
